export const FETCH_RESELLERS_REQUEST = 'FETCH_RESELLERS_REQUEST';
export const FETCH_RESELLERS_SUCCESS = 'FETCH_RESELLERS_SUCCESS';
export const FETCH_RESELLERS_FAIL = 'FETCH_RESELLERS_FAIL';

export const ADD_RESELLER_REQUEST = 'ADD_RESELLER_REQUEST';
export const ADD_RESELLER_SUCCESS = 'ADD_RESELLER_SUCCESS';
export const ADD_RESELLER_FAIL = 'ADD_RESELLER_FAIL';

export const EDIT_RESELLER_REQUEST = 'EDIT_RESELLER_REQUEST';
export const EDIT_RESELLER_SUCCESS = 'EDIT_RESELLER_SUCCESS';
export const EDIT_RESELLER_FAIL = 'EDIT_RESELLER_FAIL';

export const DELETE_RESELLER_REQUEST = 'DELETE_RESELLER_REQUEST';
export const DELETE_RESELLER_SUCCESS = 'DELETE_RESELLER_SUCCESS';
export const DELETE_RESELLER_FAIL = 'DELETE_RESELLER_FAIL';
